%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\user\Desktop\Isi\finaleVersionen\ARP_Programmcode\ARP_Programmcode\E_bus_logger_2017-01-13.csv
%
% Auto-generated by MATLAB on 02-Oct-2020 12:07:11

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [6, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Other", "Var7", "Var8"];
opts.SelectedVariableNames = "Other";
opts.VariableTypes = ["string", "string", "string", "string", "string", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var7", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var7", "Var8"], "EmptyFieldRule", "auto");

% Import the data
Ebuslogger20170113 = readtable("C:\Users\user\Desktop\Isi\finaleVersionen\ARP_Programmcode\ARP_Programmcode\E_bus_logger_2017-01-13.csv", opts);

%% Convert to output type
Geschwindigkeit = timeseries(table2array(Ebuslogger20170113));

%% Clear temporary variables
clear opts